### ISSUE TITLE
Logout if spam

### ISSUE THREAD

**Issue by cyberS7** [layer7be/vue-starter#8]
If you log in, then go to Dogs ant try to spam with clicking Dog List and after that Create One. Try to repeat clicking Dog List - Create One - Dog List - Create One one more time. After that jwt-token will be removed from localStorage, user will be logout and in console you see "[Vue warn]: Error when evaluating expression "$root.user.name". Turn on debug mode to see stack trace."

**Comment by kcalliauw** [comment]
You can avoid this issue by increasing the grace_period on the Laravel end. Since everything is async you may run into a problem with token lifetime. The warning is normal (and expected) because the user is unset when a 401 is returned from the API. Before the redirect happens, user.name is addressed but doesn't exist anymore. 
For the jwt-auth relevant issue: check here: 
https://github.com/tymondesigns/jwt-auth/issues/301
